name: "run releases"
on:
  push:
    branches:
      - 'releases/**'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: test simple
        uses: sarisia/actions-status-discord@releases/v1
        with:
          status: ${{ job.status }}
      - name: test full
        uses: sarisia/actions-status-discord@releases/v1
        with:
          status: Failure
          title: Test release branch
          description: "testing `releases/v1` branch"
          nofail: false
          nodetail: false
          color: 0xFFFFFF
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}
      - name: test nodetail
        uses: sarisia/actions-status-discord@releases/v1
        with:
          status: Cancelled
          title: test nodetail
          nodetail: true
          nofail: false
